# Generated by Django 3.2.13 on 2022-09-04 04:23

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Data & Hora registrado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Data & Hora modificado')),
                ('desactivate_at', models.DateTimeField(auto_now=True, verbose_name='Data & Hora desativado')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Título')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique_with=['title'])),
                ('description', models.TextField(max_length=2000, verbose_name='Descrição')),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Código')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_Rooms_FK', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Sala de Votação',
                'verbose_name_plural': 'Salas de Votações',
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Votation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Data & Hora registrado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Data & Hora modificado')),
                ('desactivate_at', models.DateTimeField(auto_now=True, verbose_name='Data & Hora desativado')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Título')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique_with=['title'])),
                ('description', models.TextField(max_length=2000, verbose_name='Descrição')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='Inicio')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Término')),
                ('is_user_anonimous', models.BooleanField(default=False, verbose_name='Usuário Anônimo')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votations.room', verbose_name='Sala de Votação')),
            ],
            options={
                'verbose_name': 'Votação',
                'verbose_name_plural': 'Votações',
                'db_table': 'votations',
            },
        ),
    ]
