# Generated by Django 3.2.13 on 2022-08-26 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(max_length=2000, verbose_name='Descrição')),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Código')),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Criação')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_Rooms_FK', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuários')),
            ],
            options={
                'verbose_name': 'Sala de Votação',
                'verbose_name_plural': 'Salas de Votações',
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Votation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('description', models.TextField(max_length=2000, verbose_name='Descrição')),
                ('date_init', models.DateTimeField(blank=True, null=True, verbose_name='Inicio')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Término')),
                ('is_user_anonimous', models.BooleanField(default=False, verbose_name='Usuário Anônimo')),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Criação')),
                ('rooms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votations.rooms', verbose_name='Sala de Votação')),
            ],
            options={
                'verbose_name': 'Votação',
                'verbose_name_plural': 'Votações',
                'db_table': 'votations',
            },
        ),
    ]
