# Generated by Django 3.2.13 on 2022-09-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='desactivate_at',
            field=models.DateTimeField(blank=True, verbose_name='Data & Hora desativado'),
        ),
        migrations.AlterField(
            model_name='room',
            name='update_at',
            field=models.DateTimeField(blank=True, verbose_name='Data & Hora modificado'),
        ),
        migrations.AlterField(
            model_name='votation',
            name='desactivate_at',
            field=models.DateTimeField(blank=True, verbose_name='Data & Hora desativado'),
        ),
        migrations.AlterField(
            model_name='votation',
            name='update_at',
            field=models.DateTimeField(blank=True, verbose_name='Data & Hora modificado'),
        ),
    ]
