# Generated by Django 3.2.13 on 2022-08-29 04:04

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votation',
            old_name='date_init',
            new_name='date_starting',
        ),
        migrations.RenameField(
            model_name='votation',
            old_name='rooms',
            new_name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
        migrations.AddField(
            model_name='room',
            name='deactivate_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data & Hora desativado'),
        ),
        migrations.AddField(
            model_name='room',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=True, populate_from='get_title_slug', unique_with=['title']),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data & Hora modificado'),
        ),
        migrations.AddField(
            model_name='votation',
            name='deactivate_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data & Hora desativado'),
        ),
        migrations.AddField(
            model_name='votation',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=True, populate_from='get_title_slug', unique_with=['title']),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votation',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data & Hora modificado'),
        ),
        migrations.AlterField(
            model_name='room',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data & Hora registrado'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='votation',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data & Hora registrado'),
        ),
        migrations.AlterField(
            model_name='votation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
