# Generated by Django 3.2.13 on 2022-08-30 04:06

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votations', '0002_auto_20220829_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique_with=['title']),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='votation',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique_with=['title']),
        ),
        migrations.AlterField(
            model_name='votation',
            name='titulo',
            field=models.CharField(max_length=150, unique=True, verbose_name='Título'),
        ),
    ]
