# Generated by Django 3.2.13 on 2022-09-04 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votations', '0003_auto_20220904_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votation',
            name='room',
        ),
    ]
