# Generated by Django 3.2.13 on 2022-09-04 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votations', '0004_remove_votation_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='votation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votations.room', verbose_name='Sala de Votação'),
        ),
    ]
