# Generated by Django 3.0.13 on 2021-03-24 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20210324_1654'),
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Votar',
            new_name='Pessoa_Voto',
        ),
    ]
