# Generated by Django 3.0.13 on 2021-03-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0005_auto_20210329_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa_voto',
            name='quantidade_votos',
            field=models.IntegerField(default=0, null=True, verbose_name='Quantidade de Votos'),
        ),
    ]
