# Generated by Django 3.2.13 on 2022-08-28 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Criação')),
                ('update_at', models.DateTimeField(verbose_name='Data da Atualização')),
                ('desactive_at', models.DateTimeField(verbose_name='Data da Desativação')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_UserRooms_FK', to='votations.room', verbose_name='Sala de Votação')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuários')),
            ],
            options={
                'verbose_name': 'Sala de Usuário',
                'verbose_name_plural': 'Sala de Usuários',
                'db_table': 'user_rooms',
            },
        ),
    ]
