# Generated by Django 3.2.13 on 2022-09-04 04:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrooms',
            name='desactive_at',
        ),
        migrations.AddField(
            model_name='userrooms',
            name='desactivate_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data & Hora desativado'),
        ),
        migrations.AlterField(
            model_name='userrooms',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data & Hora registrado'),
        ),
        migrations.AlterField(
            model_name='userrooms',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='userrooms',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data & Hora modificado'),
        ),
        migrations.AlterField(
            model_name='userrooms',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuários da Sala'),
        ),
    ]
