# Generated by Django 3.0.13 on 2021-03-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_auto_20210324_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa_voto',
            options={'verbose_name': 'Voto Pessoa', 'verbose_name_plural': 'Voto das Pessoas'},
        ),
        migrations.AddField(
            model_name='pessoa_voto',
            name='quantidade_votos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='pessoa_voto',
            table='pessoa_voto',
        ),
    ]
