# Generated by Django 3.0.13 on 2021-03-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0003_auto_20210324_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa_voto',
            name='quantidade_votos',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Quantidade de Votos'),
        ),
    ]
