# Generated by Django 3.2.13 on 2022-09-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220904_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='desactivate_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data & Hora desativado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data & Hora modificado'),
        ),
    ]
