# Generated by Django 3.0.13 on 2021-03-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=194, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'db_table': 'pessoa',
            },
        ),
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=194, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=340, verbose_name='Descrição')),
                ('anonimo', models.BooleanField(default=False, verbose_name='Usuário anônimo')),
                ('voto_unico', models.BooleanField(default=False)),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Horário de chegada na portaria')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Horário de saída do condomínio')),
            ],
            options={
                'verbose_name': 'Votação',
                'verbose_name_plural': 'Votações',
                'db_table': 'votacao',
            },
        ),
        migrations.CreateModel(
            name='OpcaoVoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=194, verbose_name='Nome')),
                ('codigo', models.BooleanField(default=False, verbose_name='Usuário anônimo')),
                ('numero_votos', models.BooleanField()),
                ('votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Votacao')),
            ],
            options={
                'verbose_name': 'Opcão de Voto',
                'verbose_name_plural': 'Opções de Voto',
                'db_table': 'opcao',
            },
        ),
    ]
