# Generated by Django 3.0.13 on 2021-03-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcaovoto',
            name='numero_votos',
            field=models.IntegerField(),
        ),
    ]
