# Generated by Django 3.0.13 on 2021-06-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_auto_20210329_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacao',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Término da Votação'),
        ),
        migrations.AlterField(
            model_name='votacao',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio da Votação'),
        ),
    ]
