# Generated by Django 3.0.13 on 2021-03-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20210324_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcaovoto',
            name='numero_votos',
            field=models.PositiveSmallIntegerField(verbose_name='Número de Voto'),
        ),
    ]
