# Generated by Django 3.0.13 on 2021-03-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20210324_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcaovoto',
            name='numero_votos',
            field=models.IntegerField(default=0, verbose_name='Número de Voto'),
        ),
    ]
