# Generated by Django 3.0.13 on 2021-03-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_auto_20210324_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcaovoto',
            name='numero_votos',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Número de Voto'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
