# Generated by Django 3.0.13 on 2021-08-02 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcaoVoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=194, verbose_name='Nome:')),
                ('codigo', models.CharField(max_length=194, verbose_name='Código:')),
                ('numero_votos', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Número de Voto:')),
            ],
            options={
                'verbose_name': 'Opcão de Voto',
                'verbose_name_plural': 'Opções de Votos',
            },
        ),
        migrations.CreateModel(
            name='SalaVotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=194, verbose_name='Título:')),
                ('codigo', models.CharField(blank=True, max_length=194, null=True, unique=True, verbose_name='Código:')),
                ('data_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Data da Criação:')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name='Administrador da Sala:')),
                ('usuarios', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuarios:')),
            ],
            options={
                'verbose_name': 'Sala de Votação',
                'verbose_name_plural': 'Salas de Votações',
            },
        ),
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=194, verbose_name='Título:')),
                ('descricao', models.TextField(max_length=340, verbose_name='Descrição:')),
                ('anonimo', models.BooleanField(default=False, verbose_name='Usuário Anônimo:')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Inicio:')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Término:')),
                ('data_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Data da Criação:')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votacao.SalaVotacao', verbose_name='Sala de Votação:')),
            ],
            options={
                'verbose_name': 'Votação',
                'verbose_name_plural': 'Votações',
            },
        ),
        migrations.CreateModel(
            name='Pessoa_Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_votos', models.IntegerField(default=0, null=True, verbose_name='Quantidade de Votos')),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.OpcaoVoto')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.Votacao')),
            ],
            options={
                'verbose_name': 'Voto da Pessoa',
                'verbose_name_plural': 'Voto das Pessoas',
            },
        ),
        migrations.AddField(
            model_name='opcaovoto',
            name='votacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votacao.Votacao', verbose_name='Votação:'),
        ),
    ]
