# Generated by Django 3.0.13 on 2021-08-18 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaVoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_votos', models.IntegerField(default=0, null=True, verbose_name='Quantidade de Votos')),
                ('opcao_voto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.OpcaoVoto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.Votacao')),
            ],
            options={
                'verbose_name': 'Voto da Pessoa',
                'verbose_name_plural': 'Votos das Pessoas',
            },
        ),
        migrations.DeleteModel(
            name='Pessoa_Voto',
        ),
    ]
