# Generated by Django 3.0.13 on 2021-08-19 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votacao', '0002_auto_20210818_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcaovoto',
            name='data_registrado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data da Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opcaovoto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pessoavoto',
            name='data_registrado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data da Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoavoto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salavotacao',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='votacao',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='opcaovoto',
            name='codigo',
            field=models.CharField(max_length=10, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='opcaovoto',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='opcaovoto',
            name='numero_votos',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Número de Voto'),
        ),
        migrations.AlterField(
            model_name='opcaovoto',
            name='votacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votacao.Votacao', verbose_name='Votação'),
        ),
        migrations.AlterField(
            model_name='salavotacao',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='salavotacao',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='salavotacao',
            name='data_registrado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Criação'),
        ),
        migrations.AlterField(
            model_name='salavotacao',
            name='titulo',
            field=models.CharField(max_length=150, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='salavotacao',
            name='usuarios',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuarios'),
        ),
        migrations.AlterField(
            model_name='votacao',
            name='anonimo',
            field=models.BooleanField(default=False, verbose_name='Usuário Anônimo'),
        ),
        migrations.AlterField(
            model_name='votacao',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Término'),
        ),
        migrations.AlterField(
            model_name='votacao',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='votacao',
            name='data_registrado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Criação'),
        ),
        migrations.AlterField(
            model_name='votacao',
            name='descricao',
            field=models.TextField(max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='votacao',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votacao.SalaVotacao', verbose_name='Sala de Votação'),
        ),
        migrations.AlterField(
            model_name='votacao',
            name='titulo',
            field=models.CharField(max_length=150, verbose_name='Título'),
        ),
    ]
