# Generated by Django 3.0.13 on 2021-09-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0003_auto_20210819_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='salavotacao',
            name='descricao',
            field=models.CharField(default=1, max_length=300, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salavotacao',
            name='titulo',
            field=models.CharField(max_length=60, verbose_name='Título'),
        ),
    ]
