# Generated by Django 3.0.13 on 2021-09-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0004_auto_20210904_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salavotacao',
            name='descricao',
            field=models.TextField(max_length=300, verbose_name='Descrição'),
        ),
    ]
