# Generated by Django 3.2.7 on 2021-09-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0005_auto_20210904_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salavotacao',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='salavotacao',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
    ]
