# Generated by Django 3.2.7 on 2021-09-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0011_auto_20210916_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salavotacao',
            name='descricao',
            field=models.TextField(max_length=2000, verbose_name='Descrição'),
        ),
    ]
