# Generated by Django 3.2.7 on 2021-09-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0012_alter_salavotacao_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salavotacao',
            name='resumo',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Resumo'),
        ),
    ]
